name: Run Lambda Function Update
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: nonprod
        type: environment
      zip_archive:
        description: 'Enter the name of the zip object from S3 to deploy. Example: master.zip'
        required: true
        default: master.zip
        type: string

jobs:
  update-lambda-code:
    uses: dvsa/.github/.github/workflows/update-lambda-function.yaml@v2.2
    strategy:
      matrix:
        lambdaName: [
          create,
          delete,
          get,
          getDocumentByToken,
          list,
          sites,
          streamDocuments,
          updateMulti,
          updateWithPayment,
          getPenaltyGroup,
          deleteGroup,
          updateUponPaymentDelete,
          createPenaltyGroup,
          updatePenaltyGroupWithPayment,
          listGroups,
          searchByVehicleRegistration,
          updateMultipleUponPaymentDelete,
          updateWithPaymentStartTime,
          updatePenaltyGroupWithPaymentStartTime
        ]
    with:
      environment: ${{ github.event.inputs.environment }}
      lambda_function_name: rsp-nonprod-apis-backend-${{ matrix.lambdaName }}
      bucket_key: backend/${{ matrix.lambdaName }}/${{  github.event.inputs.zip_archive }}
    permissions:
      id-token: write
    secrets:
      AWS_ACCOUNT: ${{ secrets.RSP_AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.RSP_AWS_REGION }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}